version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:80"
    environment:
      - DB_HOST=db.wcvqfkavoqmkwyhxzesr.supabase.co
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASS=S1yX6P12trAgc75f
      - DB_NAME=postgres
    restart: unless-stopped